## 准备工作

生成稀疏矩阵

In [1]:
import numpy as np
import random
sparse=0.35
size=256 #生成方阵的大小：size*size
matrix=np.arange(size*size).reshape(size,size)
for i in range(len(matrix)):
    for j in range(len(matrix[i])):
        x=random.randint(0,100)
        if x > (100*sparse):
            matrix[i][j]=0
        else:
            matrix[i][j]=x+1
print("Generate random matirx")
print(matrix)

Generate random matirx
[[ 0  0 28 ... 36  0  0]
 [14  0  0 ... 14  0  0]
 [ 0 32  0 ...  0  0 33]
 ...
 [ 0 16  6 ...  0 29  0]
 [ 0  7  8 ...  0  0  0]
 [ 0  0 31 ...  0  9  5]]


普通矩阵转CSR矩阵函数

In [2]:
# matrix to csr format
def matrix2csr(matrix):
    row_num=0
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if matrix[i][j] != 0:
                row_num+=1
#     values=np.arange(row_num).reshape(1,row_num)
#     colIndex=np.arange(row_num).reshape(1,row_num)
#     rowPtr=np.arange(len(matrix)+1)
    values=[1]*row_num
    colIndex=[1]*row_num
    rowPtr=[1]*(len(matrix)+1)
    k=0
    l=0
    tmp_size=list(range(len(matrix)))
    for i in tmp_size:
        for j in tmp_size:
            if j==0:
                rowPtr[l]=k
                l+=1
            if matrix[i][j]!=0:
                values[k]=matrix[i][j]
                colIndex[k]=j
                k+=1
    rowPtr[l]=row_num
    return values,colIndex,rowPtr

将普通稀疏矩阵转为CSR型稀疏矩阵

In [3]:
values=[]
rowPtr=[]
colIndex=[]
values,colIndex,rowPtr=matrix2csr(matrix)

显示CSR型矩阵表示结果

In [4]:
print("值")
print(values)

值
[28, 23, 33, 36, 8, 3, 32, 16, 14, 18, 34, 28, 28, 14, 3, 20, 19, 13, 32, 30, 19, 22, 30, 17, 32, 7, 31, 15, 31, 18, 28, 33, 32, 28, 33, 28, 15, 12, 33, 18, 6, 35, 4, 12, 12, 30, 32, 21, 6, 29, 25, 34, 12, 10, 1, 10, 11, 8, 11, 27, 12, 7, 36, 11, 36, 5, 28, 28, 20, 24, 9, 13, 27, 8, 6, 10, 8, 34, 12, 19, 7, 15, 14, 18, 8, 32, 27, 32, 36, 14, 13, 31, 5, 26, 22, 18, 15, 19, 11, 6, 6, 13, 17, 9, 2, 2, 1, 34, 11, 29, 2, 12, 21, 11, 36, 36, 29, 2, 18, 28, 7, 2, 5, 10, 12, 28, 30, 19, 33, 23, 30, 29, 33, 28, 35, 18, 7, 5, 1, 28, 35, 14, 31, 32, 11, 18, 4, 32, 27, 34, 19, 27, 34, 32, 30, 7, 3, 28, 20, 6, 7, 2, 6, 17, 24, 26, 31, 29, 12, 10, 24, 8, 25, 16, 32, 33, 15, 29, 15, 19, 22, 19, 18, 12, 13, 35, 14, 32, 13, 12, 8, 16, 36, 25, 16, 10, 30, 28, 16, 23, 27, 30, 24, 10, 17, 1, 14, 17, 30, 3, 16, 8, 8, 16, 2, 5, 28, 34, 8, 12, 27, 1, 2, 19, 2, 32, 32, 31, 21, 4, 22, 3, 6, 18, 21, 12, 24, 6, 11, 22, 3, 10, 31, 2, 30, 32, 17, 31, 3, 14, 8, 12, 13, 23, 7, 35, 28, 18, 10, 10, 1, 12, 4, 33, 21,

In [5]:
print("列索引")
print(colIndex)

列索引
[2, 3, 4, 6, 7, 13, 14, 15, 17, 19, 21, 25, 27, 30, 37, 40, 47, 49, 57, 63, 65, 68, 69, 71, 75, 76, 81, 83, 84, 86, 89, 92, 93, 95, 96, 97, 104, 106, 119, 121, 126, 130, 132, 133, 136, 138, 145, 149, 151, 152, 153, 154, 156, 159, 163, 165, 168, 176, 179, 180, 182, 189, 190, 191, 193, 197, 199, 200, 201, 204, 208, 213, 216, 218, 219, 220, 226, 230, 233, 235, 237, 238, 239, 240, 241, 243, 246, 249, 253, 0, 5, 6, 8, 11, 12, 15, 17, 19, 20, 21, 24, 26, 27, 28, 30, 34, 35, 37, 47, 50, 53, 54, 58, 59, 60, 61, 62, 65, 66, 69, 73, 83, 85, 86, 90, 94, 96, 97, 98, 101, 105, 107, 113, 114, 116, 117, 121, 122, 124, 125, 130, 133, 135, 140, 141, 149, 150, 153, 155, 158, 160, 162, 164, 169, 172, 179, 183, 184, 185, 187, 191, 193, 194, 196, 197, 198, 203, 205, 206, 212, 217, 218, 219, 220, 227, 228, 229, 232, 233, 234, 238, 239, 241, 247, 248, 249, 253, 1, 5, 11, 15, 19, 20, 21, 24, 26, 35, 36, 39, 41, 43, 46, 48, 50, 53, 56, 59, 61, 63, 64, 65, 66, 71, 74, 76, 78, 82, 84, 85, 90, 94, 97, 99, 100

In [6]:
print("行索引")
print(rowPtr)

行索引
[0, 89, 187, 280, 379, 472, 559, 654, 738, 822, 915, 997, 1088, 1190, 1277, 1364, 1454, 1552, 1643, 1735, 1823, 1916, 2009, 2098, 2183, 2266, 2359, 2465, 2552, 2641, 2736, 2825, 2925, 3010, 3097, 3197, 3297, 3383, 3491, 3583, 3668, 3754, 3845, 3940, 4029, 4120, 4211, 4316, 4415, 4506, 4594, 4680, 4774, 4850, 4952, 5049, 5141, 5234, 5317, 5398, 5494, 5586, 5686, 5783, 5870, 5963, 6045, 6158, 6233, 6324, 6420, 6508, 6587, 6678, 6767, 6858, 6946, 7032, 7107, 7197, 7292, 7376, 7447, 7534, 7633, 7730, 7824, 7928, 8013, 8113, 8208, 8300, 8393, 8496, 8583, 8683, 8770, 8875, 8971, 9064, 9160, 9260, 9346, 9440, 9531, 9620, 9714, 9805, 9884, 9987, 10072, 10156, 10243, 10345, 10432, 10504, 10596, 10674, 10776, 10858, 10954, 11051, 11136, 11223, 11318, 11402, 11493, 11579, 11666, 11750, 11828, 11912, 12006, 12100, 12191, 12291, 12378, 12466, 12540, 12628, 12725, 12808, 12901, 12994, 13066, 13153, 13248, 13326, 13426, 13516, 13610, 13705, 13792, 13887, 13992, 14096, 14208, 14306, 14395, 14485, 

将values的值转化为标准float32格式

In [7]:
# for i in list(range(len(values))):
#     values[i]=np.float32(values[i])
values=np.float32(values)

得到values的单精度浮点数表示：

In [8]:
print(values)

[28. 23. 33. ...  6.  9.  5.]


生成随机向量

In [9]:
vec=[1]*size
for i in list(range(len(vec))):
    vec[i]=random.randint(0,100)-20
    #vec[i]=np.float32(vec[i])
vec=np.float32(vec)

In [10]:
print("随机向量：")
print(vec)

随机向量：
[ 75.  48.  14.  11.  28.   0.  79.  -6.  73.  65.  79.   6.  79.  77.
  19.  50. -11. -11.  46.  31.   9.  54.  -6.  38.  39. -16.  36.  37.
  52.  59.  55.  74.  50. -14.  39.   5.  16.  53. -15.  53.  55.  47.
  14.  47.  18.  72.   3.  15.  28.  45.  67.  14.  45.  59. -20.  36.
  12.   8.  21.  41.  53.  27.  40.  75.  55.  24. -16.  21.  38.   2.
  25.  -6.  59.  48.  25.  59.  39.  36. -11. -19.  11.  74.  37.  19.
   1.  60.  56. -17.  -9.  31.  59.  47.  26.  48.  61.  44. -19.  60.
  77. -10.  80. -19.  48. -16.  36.  18.  38.  46.  41.   8.  59.  41.
   8. -19.  -7.  14.  59.  35.  58.   7.  61.  44.  59.  -1.   6.  58.
  -2.  27.   0.  44.  -8.  25. -14.  -4.  26. -11.  50.  54.   1.  54.
  70.  45.  -1.   3.  49.  20.  54.  70.  71.  63.  56.  33.  44.  56.
  10.  72.   8.  67.  64.  -1.  23. -10. -20.  31.  31. -16.  26.  41.
 -14.  41.   4.  59.  20.  62.   1.  -3.  69.  38.  23.   5.  10.  80.
  78.  60.  36.   3.  22.  15.  27.   9.  33.  61. -19.   0.  34.  46.


## 使用Python计算稀疏矩阵乘法

In [11]:
# 数据备份
mat=matrix
val=values
col=colIndex
row=rowPtr
number=vec

运算前再次检查原始数据：

In [12]:
print(mat)

[[ 0  0 28 ... 36  0  0]
 [14  0  0 ... 14  0  0]
 [ 0 32  0 ...  0  0 33]
 ...
 [ 0 16  6 ...  0 29  0]
 [ 0  7  8 ...  0  0  0]
 [ 0  0 31 ...  0  9  5]]


In [13]:
print(val)

[28. 23. 33. ...  6.  9.  5.]


In [14]:
print(col)

[2, 3, 4, 6, 7, 13, 14, 15, 17, 19, 21, 25, 27, 30, 37, 40, 47, 49, 57, 63, 65, 68, 69, 71, 75, 76, 81, 83, 84, 86, 89, 92, 93, 95, 96, 97, 104, 106, 119, 121, 126, 130, 132, 133, 136, 138, 145, 149, 151, 152, 153, 154, 156, 159, 163, 165, 168, 176, 179, 180, 182, 189, 190, 191, 193, 197, 199, 200, 201, 204, 208, 213, 216, 218, 219, 220, 226, 230, 233, 235, 237, 238, 239, 240, 241, 243, 246, 249, 253, 0, 5, 6, 8, 11, 12, 15, 17, 19, 20, 21, 24, 26, 27, 28, 30, 34, 35, 37, 47, 50, 53, 54, 58, 59, 60, 61, 62, 65, 66, 69, 73, 83, 85, 86, 90, 94, 96, 97, 98, 101, 105, 107, 113, 114, 116, 117, 121, 122, 124, 125, 130, 133, 135, 140, 141, 149, 150, 153, 155, 158, 160, 162, 164, 169, 172, 179, 183, 184, 185, 187, 191, 193, 194, 196, 197, 198, 203, 205, 206, 212, 217, 218, 219, 220, 227, 228, 229, 232, 233, 234, 238, 239, 241, 247, 248, 249, 253, 1, 5, 11, 15, 19, 20, 21, 24, 26, 35, 36, 39, 41, 43, 46, 48, 50, 53, 56, 59, 61, 63, 64, 65, 66, 71, 74, 76, 78, 82, 84, 85, 90, 94, 97, 99, 100, 10

In [15]:
print(row)

[0, 89, 187, 280, 379, 472, 559, 654, 738, 822, 915, 997, 1088, 1190, 1277, 1364, 1454, 1552, 1643, 1735, 1823, 1916, 2009, 2098, 2183, 2266, 2359, 2465, 2552, 2641, 2736, 2825, 2925, 3010, 3097, 3197, 3297, 3383, 3491, 3583, 3668, 3754, 3845, 3940, 4029, 4120, 4211, 4316, 4415, 4506, 4594, 4680, 4774, 4850, 4952, 5049, 5141, 5234, 5317, 5398, 5494, 5586, 5686, 5783, 5870, 5963, 6045, 6158, 6233, 6324, 6420, 6508, 6587, 6678, 6767, 6858, 6946, 7032, 7107, 7197, 7292, 7376, 7447, 7534, 7633, 7730, 7824, 7928, 8013, 8113, 8208, 8300, 8393, 8496, 8583, 8683, 8770, 8875, 8971, 9064, 9160, 9260, 9346, 9440, 9531, 9620, 9714, 9805, 9884, 9987, 10072, 10156, 10243, 10345, 10432, 10504, 10596, 10674, 10776, 10858, 10954, 11051, 11136, 11223, 11318, 11402, 11493, 11579, 11666, 11750, 11828, 11912, 12006, 12100, 12191, 12291, 12378, 12466, 12540, 12628, 12725, 12808, 12901, 12994, 13066, 13153, 13248, 13326, 13426, 13516, 13610, 13705, 13792, 13887, 13992, 14096, 14208, 14306, 14395, 14485, 1457

In [16]:
print(number)

[ 75.  48.  14.  11.  28.   0.  79.  -6.  73.  65.  79.   6.  79.  77.
  19.  50. -11. -11.  46.  31.   9.  54.  -6.  38.  39. -16.  36.  37.
  52.  59.  55.  74.  50. -14.  39.   5.  16.  53. -15.  53.  55.  47.
  14.  47.  18.  72.   3.  15.  28.  45.  67.  14.  45.  59. -20.  36.
  12.   8.  21.  41.  53.  27.  40.  75.  55.  24. -16.  21.  38.   2.
  25.  -6.  59.  48.  25.  59.  39.  36. -11. -19.  11.  74.  37.  19.
   1.  60.  56. -17.  -9.  31.  59.  47.  26.  48.  61.  44. -19.  60.
  77. -10.  80. -19.  48. -16.  36.  18.  38.  46.  41.   8.  59.  41.
   8. -19.  -7.  14.  59.  35.  58.   7.  61.  44.  59.  -1.   6.  58.
  -2.  27.   0.  44.  -8.  25. -14.  -4.  26. -11.  50.  54.   1.  54.
  70.  45.  -1.   3.  49.  20.  54.  70.  71.  63.  56.  33.  44.  56.
  10.  72.   8.  67.  64.  -1.  23. -10. -20.  31.  31. -16.  26.  41.
 -14.  41.   4.  59.  20.  62.   1.  -3.  69.  38.  23.   5.  10.  80.
  78.  60.  36.   3.  22.  15.  27.   9.  33.  61. -19.   0.  34.  46.
  72. 

In [17]:
# 保存测试结果的变量
original_res=[1]*(len(number))
csr_res=[1]*(len(number))

In [18]:
def matrix_mul_vector(matrix,x,y):
    n=list(range(len(matrix)))
    for i in n:
        y0=0.0
        for j in n:
            y0+=matrix[i][j]*x[j]
        y[i]=y0

In [19]:
def spmv(rowPtr,colIndex,values,x,y):
    num_rows=list(range(len(x)))
    for i in num_rows:
        y0=0.0
        k=rowPtr[i]
        while k<rowPtr[i+1]:
            y0+=values[k]*x[colIndex[k]]
            k+=1
        y[i]=y0

In [20]:
# 使用普通矩阵乘法
matrix_mul_vector(mat,number,original_res)
print(original_res)

[54253.0, 62051.0, 57184.0, 62344.0, 50656.0, 49913.0, 51069.0, 41737.0, 63931.0, 52498.0, 48389.0, 60429.0, 64665.0, 41302.0, 57830.0, 45507.0, 57581.0, 47690.0, 57857.0, 46077.0, 62277.0, 59532.0, 48316.0, 47797.0, 44785.0, 59644.0, 57339.0, 48486.0, 54457.0, 55893.0, 58264.0, 57523.0, 52952.0, 41710.0, 51816.0, 61780.0, 47344.0, 65132.0, 54518.0, 42007.0, 44982.0, 54965.0, 49928.0, 44259.0, 44653.0, 46778.0, 70855.0, 71863.0, 54337.0, 49087.0, 43264.0, 50431.0, 43933.0, 54333.0, 53512.0, 61644.0, 50476.0, 45619.0, 55269.0, 66885.0, 65307.0, 59962.0, 59728.0, 46815.0, 49254.0, 52699.0, 62156.0, 48237.0, 49838.0, 57210.0, 49248.0, 51996.0, 54784.0, 54901.0, 56502.0, 51484.0, 50896.0, 46182.0, 64547.0, 45847.0, 47461.0, 38779.0, 49626.0, 64452.0, 60992.0, 45524.0, 55368.0, 44839.0, 56442.0, 59484.0, 53092.0, 55254.0, 55276.0, 37697.0, 52491.0, 67117.0, 74037.0, 52557.0, 66412.0, 48427.0, 61321.0, 58800.0, 58842.0, 55685.0, 52036.0, 46523.0, 51200.0, 45882.0, 67344.0, 51721.0, 50478.0, 

In [21]:
# 使用CSR乘法计算
spmv(row,col,val,number,csr_res)
print(csr_res)

[54253.0, 62051.0, 57184.0, 62344.0, 50656.0, 49913.0, 51069.0, 41737.0, 63931.0, 52498.0, 48389.0, 60429.0, 64665.0, 41302.0, 57830.0, 45507.0, 57581.0, 47690.0, 57857.0, 46077.0, 62277.0, 59532.0, 48316.0, 47797.0, 44785.0, 59644.0, 57339.0, 48486.0, 54457.0, 55893.0, 58264.0, 57523.0, 52952.0, 41710.0, 51816.0, 61780.0, 47344.0, 65132.0, 54518.0, 42007.0, 44982.0, 54965.0, 49928.0, 44259.0, 44653.0, 46778.0, 70855.0, 71863.0, 54337.0, 49087.0, 43264.0, 50431.0, 43933.0, 54333.0, 53512.0, 61644.0, 50476.0, 45619.0, 55269.0, 66885.0, 65307.0, 59962.0, 59728.0, 46815.0, 49254.0, 52699.0, 62156.0, 48237.0, 49838.0, 57210.0, 49248.0, 51996.0, 54784.0, 54901.0, 56502.0, 51484.0, 50896.0, 46182.0, 64547.0, 45847.0, 47461.0, 38779.0, 49626.0, 64452.0, 60992.0, 45524.0, 55368.0, 44839.0, 56442.0, 59484.0, 53092.0, 55254.0, 55276.0, 37697.0, 52491.0, 67117.0, 74037.0, 52557.0, 66412.0, 48427.0, 61321.0, 58800.0, 58842.0, 55685.0, 52036.0, 46523.0, 51200.0, 45882.0, 67344.0, 51721.0, 50478.0, 

## 加载Overlay模块
使用overlay模块进行ARM CPU与FPGA PL部分的交互

In [22]:
from pynq import Overlay
overlay=Overlay("spmv.bit")
spmul=overlay.spmv_0

## 分配内存供IP使用
`使用pynq.allocate`函数分配内存空间

In [23]:
from pynq import allocate
values_len=len(values)
rowPtr_len=len(rowPtr)
colIndex_len=len(colIndex)
vec_len=len(vec)

# 开辟存储空间
values_buffer=allocate(shape=(values_len,),dtype=np.float32)
vec_buffer=allocate(shape=(vec_len,),dtype=np.float32)
output_buffer=allocate(shape=(vec_len,),dtype=np.float32)
col_buffer=allocate(shape=(colIndex_len,),dtype=np.int32)
row_buffer=allocate(shape=(rowPtr_len,),dtype=np.int32)


将数据复制到刚开辟的内存中

In [24]:
np.copyto(values_buffer,np.float32(values))
np.copyto(vec_buffer,np.float32(vec))
np.copyto(col_buffer,np.int32(colIndex))
np.copyto(row_buffer,np.int32(rowPtr))

In [25]:
print(values_buffer)
print(vec_buffer)
print(col_buffer)
print(row_buffer)
print(output_buffer)

[28. 23. 33. ...  6.  9.  5.]
[ 75.  48.  14.  11.  28.   0.  79.  -6.  73.  65.  79.   6.  79.  77.
  19.  50. -11. -11.  46.  31.   9.  54.  -6.  38.  39. -16.  36.  37.
  52.  59.  55.  74.  50. -14.  39.   5.  16.  53. -15.  53.  55.  47.
  14.  47.  18.  72.   3.  15.  28.  45.  67.  14.  45.  59. -20.  36.
  12.   8.  21.  41.  53.  27.  40.  75.  55.  24. -16.  21.  38.   2.
  25.  -6.  59.  48.  25.  59.  39.  36. -11. -19.  11.  74.  37.  19.
   1.  60.  56. -17.  -9.  31.  59.  47.  26.  48.  61.  44. -19.  60.
  77. -10.  80. -19.  48. -16.  36.  18.  38.  46.  41.   8.  59.  41.
   8. -19.  -7.  14.  59.  35.  58.   7.  61.  44.  59.  -1.   6.  58.
  -2.  27.   0.  44.  -8.  25. -14.  -4.  26. -11.  50.  54.   1.  54.
  70.  45.  -1.   3.  49.  20.  54.  70.  71.  63.  56.  33.  44.  56.
  10.  72.   8.  67.  64.  -1.  23. -10. -20.  31.  31. -16.  26.  41.
 -14.  41.   4.  59.  20.  62.   1.  -3.  69.  38.  23.   5.  10.  80.
  78.  60.  36.   3.  22.  15.  27.   9.  33.  

In [26]:
print(values_buffer.physical_address)
print(output_buffer.physical_address)

377880576
377790464


使用IP的`write`方法，写入到IP对应的位置上

In [27]:
spmul.s_axi_control.write(0x10,row_buffer.physical_address)
spmul.s_axi_control.write(0x1c,col_buffer.physical_address)
spmul.s_axi_control.write(0x28,values_buffer.physical_address)
spmul.s_axi_control.write(0x40,vec_buffer.physical_address)
spmul.s_axi_control.write(0x34,output_buffer.physical_address)

## 启动IP
启动位于0x00的控制信号

In [28]:
import time
spmul.s_axi_CTRL.write(0x00,0x01)
while True:
    reg=spmul.s_axi_CTRL.read(0x00)
    if reg != 1:
        break
print("运行结束")

运行结束


显示计算结果：

In [29]:
#print(output_buffer)
spmul.s_axi_control.read(0x34)
tmp=list(range(vec_len))
for i in tmp:
    print(output_buffer[i])

54253.0
62051.0
57184.0
62344.0
50656.0
49913.0
51069.0
41737.0
63931.0
52498.0
48389.0
60429.0
64665.0
41302.0
57830.0
45507.0
57581.0
47690.0
57857.0
46077.0
62277.0
59532.0
48316.0
47797.0
44785.0
59644.0
57339.0
48486.0
54457.0
55893.0
58264.0
57523.0
52952.0
41710.0
51816.0
61780.0
47344.0
65132.0
54518.0
42007.0
44982.0
54965.0
49928.0
44259.0
44653.0
46778.0
70855.0
71863.0
54337.0
49087.0
43264.0
50431.0
43933.0
54333.0
53512.0
61644.0
50476.0
45619.0
55269.0
66885.0
65307.0
59962.0
59728.0
46815.0
49254.0
52699.0
62156.0
48237.0
49838.0
57210.0
49248.0
51996.0
54784.0
54901.0
56502.0
51484.0
50896.0
46182.0
64547.0
45847.0
47461.0
38779.0
49626.0
64452.0
60992.0
45524.0
55368.0
44839.0
56442.0
59484.0
53092.0
55254.0
55276.0
37697.0
52491.0
67117.0
74037.0
52557.0
66412.0
48427.0
61321.0
58800.0
58842.0
55685.0
52036.0
46523.0
51200.0
45882.0
67344.0
51721.0
50478.0
58012.0
74662.0
43457.0
37705.0
56772.0
48930.0
73536.0
44718.0
52445.0
63370.0
45669.0
49962.0
69494.0
51808.0


## 比较计算结果

In [30]:
if len(output_buffer)!=len(csr_res):
    print("长度不等，计算结果有误")
length_list=list(range(len(csr_res)))
equal=True
for i in length_list:
    if output_buffer[i]!=csr_res[i]:
        equal=False

if equal:
    print("计算结果正确")
else:
    print("计算结果错误")

计算结果正确
